services:
  mysql:
    image: mysql:8.0
    command: mysqld --sql_mode="" --secure_file_priv="/var/lib/mysql-files"
    container_name: infra_mysql_8_0
    volumes:
      - ../../datas/mysql_8_0/datas:/var/lib/mysql
      - ./configuration/conf.d:/etc/mysql/conf.d
      - ../../datas/mysql_8_0/files:/var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - databases

networks:
  databases:
    external: true


