services:
  mailhog:
    container_name: infra_mailhog
    image: mailhog/mailhog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailer.docker.localhost`)"
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external : true