services:
  mailhog:
    container_name: infra_mailhog
    image: mailhog/mailhog
    ports:
      - 10025:1025
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailer.docker.localhost`)"
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.routers.mailhog.entrypoints=websecure"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - mailhog

networks:
  traefik:
    external : true
  mailhog:
    external: true