# app|repo|type|base|compose|install
myprojekt-app|/home/webadmin/Project/MyProjekt/app.myprojekt.fr|symfony|develop|.docker/docker-compose.yml|make install
bifacto-doc|/home/webadmin/Project/Diplam09/doc.bifacto.com|symfony|develop|.docker/docker-compose.yml|make install
consotrust|/home/webadmin/Project/2JDB/stream.consotrust.com|symfony|develop|.docker/docker-compose.yml|make install
lagestionenligne|/home/webadmin/Project/LaGestionEnLigne/app.lagestionenligne.fr|symfony|develop|.docker/docker-compose.yml|make install
parisrental|/home/webadmin/Project/Asteria/parisrental.com|symfony|develop|.docker/docker-compose.yml|make install
