services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: infra_phpmyadmin
    environment:
      - PMA_HOSTS=infra_mysql_8_0
      - PMA_VERBOSES=Serveur SQL 8.0
      - UPLOAD_LIMIT=300M
    volumes:
      - ./configuration/config.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./configuration/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - databases

networks:
  databases:
    external: true
  traefik:
    external : true