services:
  reverse-proxy:
    image: traefik:v2.11
    container_name: infra_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/:/logs/
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./config/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml
      - ./certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.http.routers.traefik.tls=true"
    networks:
      - traefik

networks:
  traefik:
    external: true
